# Generated by Django 6.1.1 on 2026-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('waste_name', models.CharField(max_length=100)),
                ('waste_type', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
    ]
